<?php

declare(strict_types=1);

namespace Migrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20240412083929 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE admins (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, birthdate DATETIME NOT NULL, gender VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, contact_number VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, storage_filename VARCHAR(255) NOT NULL, is_head_admin TINYINT(1) DEFAULT 0 NOT NULL, profile_picture VARCHAR(255) DEFAULT \'default-picture.jpg\' NOT NULL, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admission_form_olds (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) NOT NULL, patientName VARCHAR(255) NOT NULL, doctorName VARCHAR(255) NOT NULL, symptoms VARCHAR(255) NOT NULL, date_created DATETIME NOT NULL, blood_pressure VARCHAR(255) NOT NULL, temperature VARCHAR(255) NOT NULL, weight VARCHAR(255) NOT NULL, respiratory_rate VARCHAR(255) NOT NULL, pulse_rate VARCHAR(255) NOT NULL, oxygen_saturation VARCHAR(255) NOT NULL, diagnosis VARCHAR(255) NOT NULL, INDEX IDX_AE2F4AF663DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE admission_forms (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) NOT NULL, symptoms VARCHAR(255) NOT NULL, blood_pressure VARCHAR(255) NOT NULL, temperature VARCHAR(255) NOT NULL, weight VARCHAR(255) NOT NULL, respiratory_rate VARCHAR(255) NOT NULL, pulse_rate VARCHAR(255) NOT NULL, oxygen_saturation VARCHAR(255) NOT NULL, diagnosis VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, admission_date DATETIME NOT NULL, INDEX IDX_DBBA9F9663DBB69 (hospital_id), INDEX IDX_DBBA9F966B899279 (patient_id), INDEX IDX_DBBA9F9687F4FB17 (doctor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE doctors (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) NOT NULL, birthdate DATETIME NOT NULL, gender VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, profile_picture VARCHAR(255) DEFAULT \'default-picture.jpg\' NOT NULL, status VARCHAR(255) DEFAULT \'2\' NOT NULL, is_archived TINYINT(1) DEFAULT 0 NOT NULL, emp_filename VARCHAR(255) NOT NULL, id_filename VARCHAR(255) NOT NULL, storage_emp_filename VARCHAR(255) NOT NULL, storage_id_filename VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, approved_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B67687BE63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE hospitals (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, contact_number VARCHAR(255) NOT NULL, filename VARCHAR(255) NOT NULL, hospital_filename VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, storage_filename VARCHAR(255) NOT NULL, hospital_storage_filename VARCHAR(255) NOT NULL, status VARCHAR(255) DEFAULT \'2\' NOT NULL, is_archived TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, approved_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, profile_picture VARCHAR(255) DEFAULT \'default-picture.jpeg\' NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE medical_certificates (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, cerificate_date DATETIME NOT NULL, impression VARCHAR(255) NOT NULL, purpose VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A8DBD03063DBB69 (hospital_id), INDEX IDX_A8DBD0306B899279 (patient_id), INDEX IDX_A8DBD03087F4FB17 (doctor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE patients (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, birthdate DATETIME NOT NULL, gender VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, contact VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL, guardian_name VARCHAR(255) DEFAULT NULL, contact_guard VARCHAR(255) DEFAULT NULL, philhealth_no VARCHAR(255) DEFAULT NULL, id_filename VARCHAR(255) NOT NULL, id_storage_filename VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, profile_picture VARCHAR(255) DEFAULT \'default-picture.jpg\' NOT NULL, approved_at DATETIME DEFAULT NULL, is_archived TINYINT(1) DEFAULT 1 NOT NULL, status VARCHAR(255) DEFAULT \'1\' NOT NULL, INDEX IDX_2CCC2E2C63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE prenatal_checkups (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) NOT NULL, last_menstrual_date DATETIME NOT NULL, confine_date_estimated DATETIME NOT NULL, fetal_heart_tones VARCHAR(255) NOT NULL, gravida VARCHAR(255) NOT NULL, para VARCHAR(255) NOT NULL, labaratory VARCHAR(255) DEFAULT \'NA\' NOT NULL, urinalysis VARCHAR(255) DEFAULT \'NA\' NOT NULL, blood_count VARCHAR(255) DEFAULT \'NA\' NOT NULL, fecalysis VARCHAR(255) DEFAULT \'NA\' NOT NULL, isPrescribed TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, checkup_date DATETIME NOT NULL, INDEX IDX_F899A7E363DBB69 (hospital_id), INDEX IDX_F899A7E36B899279 (patient_id), INDEX IDX_F899A7E387F4FB17 (doctor_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE admission_form_olds ADD CONSTRAINT FK_AE2F4AF663DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE admission_forms ADD CONSTRAINT FK_DBBA9F9663DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE admission_forms ADD CONSTRAINT FK_DBBA9F966B899279 FOREIGN KEY (patient_id) REFERENCES patients (id)');
        $this->addSql('ALTER TABLE admission_forms ADD CONSTRAINT FK_DBBA9F9687F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctors (id)');
        $this->addSql('ALTER TABLE doctors ADD CONSTRAINT FK_B67687BE63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE medical_certificates ADD CONSTRAINT FK_A8DBD03063DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE medical_certificates ADD CONSTRAINT FK_A8DBD0306B899279 FOREIGN KEY (patient_id) REFERENCES patients (id)');
        $this->addSql('ALTER TABLE medical_certificates ADD CONSTRAINT FK_A8DBD03087F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctors (id)');
        $this->addSql('ALTER TABLE patients ADD CONSTRAINT FK_2CCC2E2C63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE prenatal_checkups ADD CONSTRAINT FK_F899A7E363DBB69 FOREIGN KEY (hospital_id) REFERENCES hospitals (id)');
        $this->addSql('ALTER TABLE prenatal_checkups ADD CONSTRAINT FK_F899A7E36B899279 FOREIGN KEY (patient_id) REFERENCES patients (id)');
        $this->addSql('ALTER TABLE prenatal_checkups ADD CONSTRAINT FK_F899A7E387F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctors (id)');
        $this->addSql('ALTER TABLE admission_form DROP FOREIGN KEY FK_E3C307F63DBB69');
        $this->addSql('ALTER TABLE admission_form DROP FOREIGN KEY FK_E3C307F6B899279');
        $this->addSql('ALTER TABLE admission_form DROP FOREIGN KEY FK_E3C307F87F4FB17');
        $this->addSql('ALTER TABLE admission_form_old DROP FOREIGN KEY FK_F14ACCBD63DBB69');
        $this->addSql('ALTER TABLE doctor DROP FOREIGN KEY FK_1FC0F36A63DBB69');
        $this->addSql('ALTER TABLE medical_certificate DROP FOREIGN KEY FK_B36515F863DBB69');
        $this->addSql('ALTER TABLE medical_certificate DROP FOREIGN KEY FK_B36515F86B899279');
        $this->addSql('ALTER TABLE medical_certificate DROP FOREIGN KEY FK_B36515F887F4FB17');
        $this->addSql('ALTER TABLE patient DROP FOREIGN KEY FK_1ADAD7EB63DBB69');
        $this->addSql('ALTER TABLE prenatal_checkup DROP FOREIGN KEY FK_F463FA8863DBB69');
        $this->addSql('ALTER TABLE prenatal_checkup DROP FOREIGN KEY FK_F463FA886B899279');
        $this->addSql('ALTER TABLE prenatal_checkup DROP FOREIGN KEY FK_F463FA8887F4FB17');
        $this->addSql('DROP TABLE `admin`');
        $this->addSql('DROP TABLE admission_form');
        $this->addSql('DROP TABLE admission_form_old');
        $this->addSql('DROP TABLE doctor');
        $this->addSql('DROP TABLE hospital');
        $this->addSql('DROP TABLE medical_certificate');
        $this->addSql('DROP TABLE patient');
        $this->addSql('DROP TABLE prenatal_checkup');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE `admin` (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, birthdate DATETIME NOT NULL, gender VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, address VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, contact_number VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, storage_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, is_head_admin TINYINT(1) DEFAULT 0 NOT NULL, profile_picture VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'default-picture.jpg\' NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME DEFAULT NULL, updated_at DATETIME DEFAULT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE admission_form (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, symptoms VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, blood_pressure VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, temperature VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, weight VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, respiratory_rate VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, pulse_rate VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, oxygen_saturation VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, diagnosis VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, admission_date DATETIME NOT NULL, INDEX IDX_E3C307F87F4FB17 (doctor_id), INDEX IDX_E3C307F6B899279 (patient_id), INDEX IDX_E3C307F63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE admission_form_old (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, patientName VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, doctorName VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, symptoms VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, date_created DATETIME NOT NULL, blood_pressure VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, temperature VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, weight VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, respiratory_rate VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, pulse_rate VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, oxygen_saturation VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, diagnosis VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_F14ACCBD63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE doctor (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, birthdate DATETIME NOT NULL, gender VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, contact VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, address VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, is_archived TINYINT(1) DEFAULT 0 NOT NULL, status VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'2\' NOT NULL COLLATE `utf8mb3_unicode_ci`, updated_at DATETIME NOT NULL, approved_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, storage_emp_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, emp_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, storage_id_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, id_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, profile_picture VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'default-picture.jpg\' NOT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_1FC0F36A63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE hospital (id INT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, password VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, contact_number VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, hospital_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, storage_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, hospital_storage_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, status VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'2\' NOT NULL COLLATE `utf8mb3_unicode_ci`, is_archived TINYINT(1) DEFAULT 0 NOT NULL, address VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, approved_at DATETIME DEFAULT NULL, profile_picture VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'default-picture.jpeg\' NOT NULL COLLATE `utf8mb3_unicode_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE medical_certificate (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, cerificate_date DATETIME NOT NULL, impression VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, purpose VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_B36515F887F4FB17 (doctor_id), INDEX IDX_B36515F86B899279 (patient_id), INDEX IDX_B36515F863DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE patient (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, name VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, birthdate DATETIME NOT NULL, password VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, gender VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, contact VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, address VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, guardian_name VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, contact_guard VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, philhealth_no VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT NULL COLLATE `utf8mb3_unicode_ci`, is_archived TINYINT(1) DEFAULT 1 NOT NULL, status VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'1\' NOT NULL COLLATE `utf8mb3_unicode_ci`, created_at DATETIME NOT NULL, approved_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, profile_picture VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'default-picture.jpg\' NOT NULL COLLATE `utf8mb3_unicode_ci`, id_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, id_storage_filename VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, INDEX IDX_1ADAD7EB63DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE prenatal_checkup (id INT UNSIGNED AUTO_INCREMENT NOT NULL, hospital_id INT UNSIGNED DEFAULT NULL, patient_id INT UNSIGNED DEFAULT NULL, doctor_id INT UNSIGNED DEFAULT NULL, family_member VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, last_menstrual_date DATETIME NOT NULL, confine_date_estimated DATETIME NOT NULL, fetal_heart_tones VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, gravida VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, para VARCHAR(255) CHARACTER SET utf8mb3 NOT NULL COLLATE `utf8mb3_unicode_ci`, labaratory VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'NA\' NOT NULL COLLATE `utf8mb3_unicode_ci`, urinalysis VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'NA\' NOT NULL COLLATE `utf8mb3_unicode_ci`, blood_count VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'NA\' NOT NULL COLLATE `utf8mb3_unicode_ci`, fecalysis VARCHAR(255) CHARACTER SET utf8mb3 DEFAULT \'NA\' NOT NULL COLLATE `utf8mb3_unicode_ci`, isPrescribed TINYINT(1) DEFAULT 0 NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, checkup_date DATETIME NOT NULL, INDEX IDX_F463FA8887F4FB17 (doctor_id), INDEX IDX_F463FA886B899279 (patient_id), INDEX IDX_F463FA8863DBB69 (hospital_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb3 COLLATE `utf8mb3_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE admission_form ADD CONSTRAINT FK_E3C307F63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_form ADD CONSTRAINT FK_E3C307F6B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_form ADD CONSTRAINT FK_E3C307F87F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctor (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_form_old ADD CONSTRAINT FK_F14ACCBD63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE doctor ADD CONSTRAINT FK_1FC0F36A63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE medical_certificate ADD CONSTRAINT FK_B36515F863DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE medical_certificate ADD CONSTRAINT FK_B36515F86B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE medical_certificate ADD CONSTRAINT FK_B36515F887F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctor (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE patient ADD CONSTRAINT FK_1ADAD7EB63DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prenatal_checkup ADD CONSTRAINT FK_F463FA8863DBB69 FOREIGN KEY (hospital_id) REFERENCES hospital (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prenatal_checkup ADD CONSTRAINT FK_F463FA886B899279 FOREIGN KEY (patient_id) REFERENCES patient (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE prenatal_checkup ADD CONSTRAINT FK_F463FA8887F4FB17 FOREIGN KEY (doctor_id) REFERENCES doctor (id) ON UPDATE NO ACTION ON DELETE NO ACTION');
        $this->addSql('ALTER TABLE admission_form_olds DROP FOREIGN KEY FK_AE2F4AF663DBB69');
        $this->addSql('ALTER TABLE admission_forms DROP FOREIGN KEY FK_DBBA9F9663DBB69');
        $this->addSql('ALTER TABLE admission_forms DROP FOREIGN KEY FK_DBBA9F966B899279');
        $this->addSql('ALTER TABLE admission_forms DROP FOREIGN KEY FK_DBBA9F9687F4FB17');
        $this->addSql('ALTER TABLE doctors DROP FOREIGN KEY FK_B67687BE63DBB69');
        $this->addSql('ALTER TABLE medical_certificates DROP FOREIGN KEY FK_A8DBD03063DBB69');
        $this->addSql('ALTER TABLE medical_certificates DROP FOREIGN KEY FK_A8DBD0306B899279');
        $this->addSql('ALTER TABLE medical_certificates DROP FOREIGN KEY FK_A8DBD03087F4FB17');
        $this->addSql('ALTER TABLE patients DROP FOREIGN KEY FK_2CCC2E2C63DBB69');
        $this->addSql('ALTER TABLE prenatal_checkups DROP FOREIGN KEY FK_F899A7E363DBB69');
        $this->addSql('ALTER TABLE prenatal_checkups DROP FOREIGN KEY FK_F899A7E36B899279');
        $this->addSql('ALTER TABLE prenatal_checkups DROP FOREIGN KEY FK_F899A7E387F4FB17');
        $this->addSql('DROP TABLE admins');
        $this->addSql('DROP TABLE admission_form_olds');
        $this->addSql('DROP TABLE admission_forms');
        $this->addSql('DROP TABLE doctors');
        $this->addSql('DROP TABLE hospitals');
        $this->addSql('DROP TABLE medical_certificates');
        $this->addSql('DROP TABLE patients');
        $this->addSql('DROP TABLE prenatal_checkups');
    }
}
